#!/bin/bash

source "$(dirname "${0}")/commons.lib"

readonly PROJECT_PATH="$(realpath "$(dirname "${0}")/../..")"
readonly PROJECT_NAME="$(basename "${PROJECT_PATH}")"

readonly GOCYCLO_VERSION="latest"
readonly GOCYCLO_REPO="github.com/fzipp/gocyclo/cmd/gocyclo"

function main() {
    local run_all="$(_read_cmd_flag "run-all" "true" "${@}")"
    local cyclo_project="$(_read_cmd_flag "cyclo" "${run_all}" "${@}")"

    if _is_truthy "${cyclo_project}"; then
        _info "Running cyclomatic complexity checks for project '${PROJECT_NAME}'..."

        _assert_success "${PROJECT_PATH}" go install -mod=mod "${GOCYCLO_REPO}@${GOCYCLO_VERSION}"
        _assert_success "${PROJECT_PATH}" gocyclo -over 10 -ignore ".*/?generated/*|vendor/" . 
    fi
}

main "${@}"