#!/bin/bash

source "$(dirname "${0}")/commons.lib"

readonly PROJECT_PATH="$(realpath "$(dirname "${0}")/../..")"
readonly PROJECT_NAME="$(basename "${PROJECT_PATH}")"

function main() {
  local run_all="$(_read_cmd_flag "run-all" "true" "${@}")"
  local run_integration_tests="$(_read_cmd_flag "integration-test" "${run_all}" "${@}")"

  if _is_truthy "${run_integration_tests}"; then
    _info "Running integration tests for project '${PROJECT_NAME}'..."

    _assert_success "${path}" go clean -testcache
    _assert_success "${path}" go test -p 1 -tags=integration ./it/... -mod=readonly -coverprofile cover.out -timeout=600s ./...
  fi
}

main "${@}"