openapi: 3.0.3
info:
  title: Weather API
  version: 1.0.0

servers:
  - url: /api

paths:
  /cities:
    get:
      description: "Return all registered cities"
      tags:
        - city
      operationId: GetAllCities
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/City"
        "400":
          description: Malformed or invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "BAD_REQUEST"
                description: "Request payload is either missing or invalid"
        "5XX":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "INTERNAL_SERVER_ERROR"
                description: "An unexpected server error occurred"
    post:
      description: "Register a city"
      tags:
        - city
      operationId: RegisterCity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/City"
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/City"
        "400":
          description: Malformed or invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "BAD_REQUEST"
                description: "Request payload is either missing or invalid"
        "5XX":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "INTERNAL_SERVER_ERROR"
                description: "An unexpected server error occurred"

  /cities/{id}:
    get:
      description: "Returns a specific city by id"
      tags:
        - city
      operationId: GetCityById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/City"
        "400":
          description: Malformed or invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "BAD_REQUEST"
                description: "Request payload is either missing or invalid"
        "410":
          description: City not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "NOT_FOUND"
                description: "The resource you requested cannot be found"
        "5XX":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "INTERNAL_SERVER_ERROR"
                description: "An unexpected server error occurred"
    put:
      description: "Updates a specific city based on its id"
      tags:
        - city
      operationId: UpdateCityById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/City"
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/City"
        "400":
          description: Malformed or invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "BAD_REQUEST"
                description: "Request payload is either missing or invalid"
        "410":
          description: City not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "NOT_FOUND"
                description: "The resource you requested cannot be found"
        "5XX":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "INTERNAL_SERVER_ERROR"
                description: "An unexpected server error occurred"
    delete:
      description: "Deletes a specific city based on its id"
      tags:
        - city
      operationId: DeleteCityById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Success.
        "400":
          description: Malformed or invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "BAD_REQUEST"
                description: "Request payload is either missing or invalid"
        "5XX":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "INTERNAL_SERVER_ERROR"
                description: "An unexpected server error occurred"

  /cities/{id}/forecasts:
    get:
      description: "Returns forecasts for a specific city and period"
      tags:
        - forecast
      operationId: GetForecastsByCityIdAndPeriod
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: period
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Forecast"
        "400":
          description: Malformed or invalid payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "BAD_REQUEST"
                description: "Request payload is either missing or invalid"
        "410":
          description: City not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "NOT_FOUND"
                description: "The resource you requested cannot be found"
        "5XX":
          description: Server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              example:
                key: "INTERNAL_SERVER_ERROR"
                description: "An unexpected server error occurred"

components:
  schemas:
    City:
      type: object
      required:
        - name
        - country
      properties:
        id:
          type: string
          example: "922613c8-60ce-42f4-9823-a0ee9df38828"
        name:
          type: string
          example: "London"
        country:
          type: string
          example: "UK"
        longitude:
          type: string
          example: "12.089"
        latitude:
          type: string
          example: "12.089"
        createdAt:
          type: integer
          readOnly: true
          format: int64
          example: 1694554228
        updatedAt:
          type: integer
          readOnly: true
          format: int64
          example: 1694557228
    Forecast:
      type: object
      required:
        - cityId
        - forecastDate
        - temperature
        - condition
      properties:
        id:
          type: string
          example: "882613c8-60ce-42f4-9823-a0ee9df38828"
        cityId:
          type: string
          example: "922613c8-60ce-42f4-9823-a0ee9df38828"
        forecastDate:
          type: string
          format: date
          example: "2024-06-01"
        temperature:
          type: string
          example: "30.0"
        condition:
          type: string
          example: "Sunny"
        createdAt:
          type: integer
          readOnly: true
          format: int64
          example: 1694554228
        updatedAt:
          type: integer
          readOnly: true
          format: int64
          example: 1694557228
    Error:
      type: object
      required:
        - key
        - description
      properties:
        key:
          type: string
          example: "BAD_REQUEST"
        description:
          type: string
          example: "Request payload is either missing or invalid"
