// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NikolNikolaeva/project_weather/services (interfaces: WeatherDataGetter)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package mocks -destination ./../mocks/mock_weather_data_getter.go . WeatherDataGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	swagger "github.com/weatherapicom/go"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWeatherDataGetter is a mock of WeatherDataGetter interface.
type MockWeatherDataGetter struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherDataGetterMockRecorder
}

func (m *MockWeatherDataGetter) GetCurrentData(q string, key string) (*swagger.Current, *swagger.Location, error) {
	//TODO implement me
	panic("implement me")
}

func (m *MockWeatherDataGetter) GetForecastData(q string, days int32, key string) (*swagger.Forecast, *swagger.Location, error) {
	//TODO implement me
	panic("implement me")
}

// MockWeatherDataGetterMockRecorder is the mock recorder for MockWeatherDataGetter.
type MockWeatherDataGetterMockRecorder struct {
	mock *MockWeatherDataGetter
}

// NewMockWeatherDataGetter creates a new mock instance.
func NewMockWeatherDataGetter(ctrl *gomock.Controller) *MockWeatherDataGetter {
	mock := &MockWeatherDataGetter{ctrl: ctrl}
	mock.recorder = &MockWeatherDataGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherDataGetter) EXPECT() *MockWeatherDataGetterMockRecorder {
	return m.recorder
}

// GetData mocks base method.
func (m *MockWeatherDataGetter) GetData(arg0 string) (*swagger.InlineResponse2001, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", arg0)
	ret0, _ := ret[0].(*swagger.InlineResponse2001)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockWeatherDataGetterMockRecorder) GetData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockWeatherDataGetter)(nil).GetData), arg0)
}
